# Generated by Django 3.1.3 on 2021-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20201123_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='screenshot',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
